# Generated by Django 3.1.7 on 2021-04-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
